### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by corkmaster** [srid/emanote-template#29]
Most certainly this is my lack of understanding and user error causing this, but setting:

 ```
 sidebar:
    collapsed: false
```
I still see no sidebar. Are there other prerequisites to get this to work? Everything else is unchanged, default theme, CSS etc.

![image](https://user-images.githubusercontent.com/119861228/206555474-3478abef-d0e3-4a53-bcc7-42f92a378cc5.png)
Thanks

**Comment by srid** [comment]
@corkmaster The problem is deeper, and nothing to do with the sidebar config. Look closely, it is not even showing Emanote rendered HTML. Looks to be something wrong with your Github Pages setup; the site is rendering using Jekyll despite Emanote [creating a `.nojekyll`](https://github.com/corkmaster/corkmaster.github.io/blob/gh-pages/.nojekyll) to tell Github to not do that.

**Comment by srid** [comment]
Go to repository settings and change your Github Pages branch to `gh-pages` (instead of `master`). That'll fix it.
